### ISSUE TITLE
production mode中出現錯誤訊息 Allpay::MissingOption: option "merchant_id" is required.

### ISSUE THREAD

**Issue by kylized** [tonytonyjan/allpay#4]
於production mode使用此gem會出現錯誤訊息。

在client.rb中的這一行：
raise MissingOption, %Q{option "#{option_name}" is required.} if @options[:option_name].nil?

將:option_name改成option_name就可以解決。
此問題是在v2.0.0版本以後發生。

By the way, nice gem, thanks.

**Comment by tonytonyjan** [comment]
你說[這個](https://github.com/tonytonyjan/allpay/blob/a894c84387b5b38c3a10557cd1919137e364df96/lib/allpay/client.rb#L95)嗎？

只是我沒有看到冒號 :confused:

**Comment by tonytonyjan** [comment]
啊啊⋯⋯我沒有 release XD

**Comment by tonytonyjan** [comment]
@kylized 你試試看 2.0.2 有沒有一樣的問題，沒有的話就 close 了，感謝！

**Comment by kylized** [comment]
剛剛測試過了v2.0.2，問題解決了～
Thumbs up!
